### ISSUE TITLE
Timeout in counting edges is not catchable

### ISSUE THREAD

**Issue by kuzeko** [ArangoDB-Community/tinkerpop-arangodb-provider#27]
When using the gremlin console, and issuing the following query

`g.E.count()`

the outcome is : 

    475837 [main] WARN  com.arangodb.http.HttpManager - The target server failed to respond
    ...
    Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)

    ... 37 more

The graph has approximately 3M edges.

I can  understand that a timeout happened (although it seems strange that this simple operation takes so long), but there is no way in the gremlin console to catch this error.

The database is running on a 24 cores machine with 128GB of memory.

The `arango.conf` file is  attached here
[arangod.conf.txt](https://github.com/arangodb/blueprints-arangodb-graph/files/670679/arangod.conf.txt)

**Comment by arcanefoam** [comment]
Closing this as the code base and versions supported have changed significantly. Please reopen if you continue to experience this issue.
